#DB
DB_LITE = 'sqlite+aiosqlite:///db.db'
DB_POSTGRES = "postgresql+asyncpg://casino_user:admin@localhost:5433/casino_db"

# TGBOT
BOT_TOKEN = '7573258681:AAEymMkDI8VSvvFVk0tK9zCpfDEWd4uSsrE'
BOT_NAME = 'cobracash_bot'
BOT_URL = 'https://t.me/cobracash_bot'
ADMIN_ID = 8068780481
CHANNEL_ID = -1002562557503
CHANNEL_USERNAME = 'Cobra_Cash'

# WEBAPP
WEBAPP_URL = 'https://cobracashbot.duckdns.org/'

# LINKS
SUP_MONEY = 'https://t.me/seregaflexr'
SUP_ERROR = 'https://t.me/seregaflexr'
SUP_REPORT = 'https://t.me/seregaflexr'
SUP_URL = 'https://t.me/seregaflexr'


# DESIGN
START_STICKER = "CAACAgIAAxkBAAEM5CJnvKzSltbdEAM1JGnAq2DPc6hmEwACVAADnP4yML83D8hHNhh3NgQ"
CABINET_PHOTO = "AgACAgIAAxkBAAPGZ9vhWwTSAAEtfJ7ET5wrL_a2GBVjAALF7TEbr2XhSoordwITcPgAAQEAAwIAA3kAAzYE"
REF_PHOTO = "AgACAgIAAxkBAAPWZ9viP1mFp7w0XC5M1v2wyQROdI8AAs7tMRuvZeFKNfuKMx4uH3sBAAMCAAN5AAM2BA"
BALANCE_PHOTO = "AgACAgIAAxkBAAPuZ9v7A16n6YCSaL1T-mCrwx_hD6oAAsHuMRvjNuBK0AjX0U27JXABAAMCAAN5AAM2BA"
SUP_PHOTO = "AgACAgIAAxkBAAP6Z9v8KNU9XgHGuS4AAbkS7Xi9TJ82AALH7jEb4zbgSvLOEN1v3gABYAEAAwIAA3kAAzYE"
BONUS_PHOTO = "AgACAgIAAxkBAAIB7WfcgTSMdkAmLB8HiIRysW-aWik5AAKm8jEb4zbgSnXvkcD5PxKDAQADAgADeQADNgQ"
